version: '3'

services:
  strapi:
    container_name: strapi-app
    image: node:18
    working_dir: /root/my-strapi-app
    volumes:
      - /root/my-strapi-app:/root/my-strapi-app
      - /root/my-strapi-app/public:/root/my-strapi-app/public
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=/root/my-strapi-app/data/db.sqlite
    command: |
      sh -c "npm install --production && npm run start"
    ports:
      - "1337:1337"
    restart: always
