version: '3'

services:
  strapi:
    container_name: strapi-app
    image: node:18
    working_dir: /my-strapi-app
    volumes:
      - /my-strapi-app:/root/my-strapi-app
      - /my-strapi-app/public:/root/my-strapi-app/public
    env_file:
      - /my-strapi-app/.env
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=/root/my-strapi-app/data/db.sqlite
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_FILENAME=${DATABASE_FILENAME}
      - APP_KEYS=${APP_KEYS}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
    command: |
      sh -c "npm install --production && npm run start"
    ports:
      - "1337:1337"
    restart: always
